import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.css";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  display: "swap",
  preload: true,
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className} antialiased`}>
      <body>
        <div className="md:max-w-7xl flex flex-col justify-between mx-auto relative"></div>
        {children}
      </body>
    </html>
  );
}
